import requests # [cite: 1804]
import logging # [cite: 1804]

# Налаштування логування для зручного відстеження помилок [cite: 1804]
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s") # [cite: 1804]

class RestClient: # [cite: 1804]
    def __init__(self, base_url, headers=None): # [cite: 1804]
        # Ініціалізує клієнт базовою URL-адресою та опціональними заголовками [cite: 1804]
        self.base_url = base_url.rstrip('/') # [cite: 1804]
        # За замовчуванням встановлюємо заголовок для роботи з JSON [cite: 1804]
        self.headers = headers if headers else {'Content-Type': 'application/json'} # [cite: 1804]

    def get(self, endpoint): # [cite: 1804]
        # Виконує HTTP GET-запит. [cite: 1804]
        url = f"{self.base_url}/{endpoint.lstrip('/')}" # [cite: 1804]
        try: # [cite: 1804]
            logging.info(f"Виконання GET-запиту до: {url}") # [cite: 1804]
            response = requests.get(url, headers=self.headers) # [cite: 1804]
            # Перевірка статус-коду. Якщо код помилки (4xx, 5xx), генерується виняток [cite: 1804]
            response.raise_for_status() # [cite: 1804]
            return response.json() # [cite: 1804]
        except requests.exceptions.HTTPError as http_err: # [cite: 1804]
            logging.error(f"HTTP помилка: {http_err} Статус код: {response.status_code}") # [cite: 1804]
        except requests.exceptions.ConnectionError as conn_err: # [cite: 1804]
            logging.error(f"Помилка з'єднання: {conn_err}") # [cite: 1804]
        except requests.exceptions.Timeout as timeout_err: # [cite: 1804]
            logging.error(f"Перевищено час очікування (Timeout): {timeout_err}") # [cite: 1804]
        except requests.exceptions.RequestException as req_err: # [cite: 1804]
            logging.error(f"Непередбачена помилка запиту: {req_err}") # [cite: 1804]
        return None # [cite: 1833]

    def post(self, endpoint, data): # [cite: 1834]
        # Виконує HTTP POST-запит з переданими даними (payload). [cite: 1835]
        url = f"{self.base_url}/{endpoint.lstrip('/')}" # [cite: 1836]
        try: # [cite: 1836]
            logging.info(f"Виконання POST-запиту до: {url}") # [cite: 1837]
            # requests автоматично серіалізує словник "data" у JSON за допомогою параметра json [cite: 1838]
            response = requests.post(url, json=data, headers=self.headers) # [cite: 1838]
            response.raise_for_status() # [cite: 1839]
            # JSONPlaceholder повертає 201 (Created) при успішному POST [cite: 1840]
            if response.status_code == 201: # [cite: 1840]
                logging.info("Ресурс успішно створено!") # [cite: 1841]
                return response.json() # [cite: 1842]
        except requests.exceptions.HTTPError as http_err: # [cite: 1843]
            logging.error(f"HTTP помилка: {http_err} Статус код: {response.status_code}") # [cite: 1844]
        except requests.exceptions.RequestException as req_err: # [cite: 1845]
            logging.error(f"Помилка запиту: {req_err}") # [cite: 1846]
        return None # [cite: 1847]

# ДЕМОНСТРАЦІЯ ВИКОРИСТАННЯ [cite: 1848, 1861]
if __name__ == "__main__": # [cite: 1856, 1864]
    # 1. Ініціалізація клієнта [cite: 1857, 1866]
    BASE_URL = "https://jsonplaceholder.typicode.com" # [cite: 1858, 1868]
    client = RestClient(base_url=BASE_URL) # [cite: 1859, 1870]

    print("-" * 50) # [cite: 1873]
    print("ТЕСТ 1: Успішний GET-запит (отримання поста з ID=1)") # [cite: 1875]
    print("-" * 50) # [cite: 1877]
    post_data = client.get("posts/1") # [cite: 1879]
    if post_data: # [cite: 1881]
        print(f"Заголовок: {post_data.get('title')}") # [cite: 1896]
        print(f"Тіло: {post_data.get('body')}") # [cite: 1897]

    print("\n" + "-" * 50) # [cite: 1898]
    print("ТЕСТ 2: Успішний POST-запит (створення нового ресурсу)") # [cite: 1909]
    print("-" * 50) # [cite: 1910]
    new_post = { # [cite: 1911]
        "title": "Мій новий пост", # [cite: 1912]
        "body": "Це тестове тіло повідомлення для перевірки методу POST.", # [cite: 1913]
        "userId": 101 # [cite: 1913]
    }
    created_post = client.post("posts", data=new_post) # [cite: 1914]
    if created_post: # [cite: 1915]
        print(f"Відповідь сервера (створений об'єкт): {created_post}") # [cite: 1916]

    print("\n" + "-" * 50) # [cite: 1917]
    print("ТЕСТ 3: Обробка помилки (GET-запит до неіснуючого ресурсу)") # [cite: 1917]
    print("-" * 50) # [cite: 1917]
    # Звертаємося до ресурсу, якого не існує (ID=9999) [cite: 1918]
    error_data = client.get("posts/9999") # [cite: 1919, 1920]
    if error_data is None: # [cite: 1904]
        print("Запит завершився невдало (отримано None), помилку оброблено коректно.") # [cite: 1921]
